server:
  port: 8088

spring:
    mvc:
        view:
          prefix: /templates/
          suffix: .html
    thymeleaf:
       cache: false
       enabled: true
       encoding: UTF-8
    servlet:
      multipart:
        enabled: true
        max-file-size: 301024MB
        max-request-size: 301024MB

logging:
  level:
    root: info
    org.springframework.web: info
    com.blospace: debug

com:
  blospace:
      config:
          filePath: upload_data
          fileName: data.json
          connstr: /ip4/192.168.31.198/tcp/5001
          hostName: http://192.168.31.198:8088
          resourcePath: file
          qrTpl: qr_tpl/cbto_tpl.png
          imageType: .jpg,.png,.jpeg,.bmp,.gif,.webp,.tiff